Repository CSE-25/quick_start_express, pull requests merged in 2024-11, with the labels that each got.

#22 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#21 Create SECURITY.md
  SECURITY.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#24 Add JS tests powered by Jest.
  .gitignore
  bin/configs.js
  bin/index.js
  package-lock.json
  package.json
  test/help.test.js
  test/list.test.js
  test/version.test.js
Labels: enhancement

#26 Add content check tests for init command.
  test/init.test.js
Labels: enhancement, help wanted

#35 Move Github docs to docs folder for better organization of files.
  README.md
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/SECURITY.md
Labels: documentation, enhancement

#36 Add `npm` badges to README.
  README.md
Labels: documentation, enhancement

#37 Update README dev setup to use a new directory for testing the templates. #33
  README.md
Labels: documentation

#38 Document steps to run jest tests.
  README.md
Labels: documentation, enhancement
