Repository CSE-25/quick_start_express, pull requests merged in 2024-10, with the labels that each got.

#8 Add CONTRIBUTING guidelines for project.
  .github/CONTRIBUTING.md
  README.md
Labels: documentation, hacktoberfest

#10 Add a Postgres template
  README.md
  bin/configs.js
  bin/index.js
  package-lock.json
  templates/express_pg_sequelize/db.js
  templates/express_pg_sequelize/index.js
  templates/express_pg_sequelize/package.json
Labels: feature, hacktoberfest, hacktoberfest-accepted

#13 Add `express_mysql` command to QSE.
  .gitignore
  bin/configs.js
  templates/express_mysql/config/appConfig.js
  templates/express_mysql/connection/normalConnection.js
  templates/express_mysql/connection/poolConnection.js
  templates/express_mysql/controller/sampleController.js
  templates/express_mysql/db/reInitDb.js
  templates/express_mysql/db/reInitDb.sql
  templates/express_mysql/index.js
  templates/express_mysql/logs/initLog.js
  templates/express_mysql/package.json
  templates/express_mysql/router/sampleRouter.js
Labels: feature, hacktoberfest
