Repository CSE-25/quick_start_express, pull requests merged in 2024-12, with the labels that each got.

#54 Update normalConnection.js
  templates/express_mysql/connection/normalConnection.js
Labels: bug-fix

#56 Add CI workflow for quick_start_express.
  .github/workflows/runJestTests.yml
  README.md
Labels: documentation, enhancement, feature

#58 Optimized test case execution time && Tests to verify the api endpoint.
  bin/index.js
  package.json
  templates/basic/server.js
  templates/basic/server.test.js
  test/help.test.js
  test/init.test.js
  test/list.test.js
  test/version.test.js
Labels: AMWOC, AMWOC-accepted

#57 feat: add -n option to customize package name during initialization
  bin/configs.js
  bin/index.js
  package.json
  templates/basic/package.json
  test/init.test.js
  test/list.test.js
Labels: AMWOC, AMWOC-accepted
