Repository CSE-25/quick_start_express, pull requests merged in 2025-02, with the labels that each got.

#106 [WIP] - Add tests for qse init command with docker-compose flag
  README.md
  bin/configs.js
  bin/index.js
  bin/util/docker.js
  bin/util/menu.js
  test/init.test.js
  test/list.test.js
Labels: enhancement, testing

#107 Refresh tokens added for GoogleOAuth template
  templates/express_oauth_google/controller/appController.js
  templates/express_oauth_google/controller/authController.js
  templates/express_oauth_google/middleware/authenticate.js
Labels: enhancement, AMWOC, AMWOC-accepted

#112 Add tests for qse init command with docker-compose flag, using cache service and db enabled
  .mise.toml
  bin/configs.js
  bin/index.js
  bin/init.js
  bin/util/docker.js
  bin/util/question/inquirer.js
  package.json
  test/init.test.js
Labels: enhancement, testing

#114 [COMPLETED] Added tests for the QSE Clear command
  test/clear.test.js
Labels: AMWOC, AMWOC-accepted, testing
