Repository CSE-25/quick_start_express, pull requests merged in 2025-01, with the labels that each got.

#61 [COMPLETED] Added express_oauth_microsoft template
  bin/configs.js
  templates/express_mysql/package.json
  templates/express_oauth_microsoft/.env
  templates/express_oauth_microsoft/controller/appController.js
  templates/express_oauth_microsoft/controller/authController.js
  templates/express_oauth_microsoft/errorHandler/errorHandler.js
  templates/express_oauth_microsoft/index.js
  templates/express_oauth_microsoft/logs/logsInit.js
  templates/express_oauth_microsoft/middleware/authenticate.js
  templates/express_oauth_microsoft/package.json
  templates/express_oauth_microsoft/router/appRouter.js
  templates/express_oauth_microsoft/router/authRouter.js
  test/init.test.js
  test/list.test.js
Labels: AMWOC, AMWOC-accepted

#63 Update README.md qse-list screenshot
  README.md
Labels: AMWOC, AMWOC-accepted

#65 Added qse-test/ and test/temp/ to .gitignore
  .gitignore
Labels: AMWOC, AMWOC-accepted

#64 [COMPLETED] Hot reload nodemon
  README.md
  bin/configs.js
  bin/index.js
  templates/basic/package.json
  templates/express_mysql/package.json
  templates/express_oauth_microsoft/package.json
  templates/express_pg_sequelize/package.json
  test/help.test.js
  test/init.test.js
  test/list.test.js
  test/version.test.js
Labels: AMWOC, AMWOC-accepted

#60 Added Express Prisma Template
  README.md
  bin/configs.js
  templates/basic/server.test.js
  templates/express_pg_prisma/.env
  templates/express_pg_prisma/.gitignore
  templates/express_pg_prisma/controllers/sampleController.ts
  templates/express_pg_prisma/db/connectDB.ts
  templates/express_pg_prisma/nodemon.json
  templates/express_pg_prisma/package.json
  templates/express_pg_prisma/prisma/migrations/20241230095743_prisma_pg/migration.sql
  templates/express_pg_prisma/prisma/migrations/migration_lock.toml
  templates/express_pg_prisma/prisma/schema.prisma
  templates/express_pg_prisma/routes/userRoutes.ts
  templates/express_pg_prisma/src/index.ts
  templates/express_pg_prisma/tsconfig.json
  templates/express_pg_prisma/util/errorHandler.ts
  templates/express_pg_prisma/util/initlog.ts
  test/init.test.js
  test/list.test.js
Labels: AMWOC, AMWOC-accepted

#73 Update README to showcase custom app name feature
  README.md
Labels: AMWOC, AMWOC-accepted

#72 [COMPLETED] Add --no-dependencies Flag to Make Dependency Installation Optional
  README.md
  bin/configs.js
  bin/index.js
  package.json
  test/init.test.js
  test/list.test.js
Labels: feature

#76 Added the express Typescript template
  README.md
  bin/configs.js
  templates/basic_ts/nodemon.json
  templates/basic_ts/package.json
  templates/basic_ts/src/index.ts
  templates/basic_ts/tsconfig.json
  test/init.test.js
  test/list.test.js
Labels: AMWOC, AMWOC-accepted

#77 [WIP] Documentation website for QSE
  .gitignore
  docs/.vitepress/config.js
  docs/getting-started.md
  docs/index.md
  docs/setup.md
  package.json
Labels: AMWOC, AMWOC-accepted

#80 Add Vitepress deployment GitHubActions workflow.
  .github/workflows/deployDocs.yml
Labels: documentation

#83 Add GH Pages URL to README.
  README.md
Labels: documentation, enhancement, AMWOC, AMWOC-accepted

#85 Questionnaire and UX Improvement
  .gitignore
  README.md
  bin/configs.js
  bin/index.js
  bin/util/menu.js
  package.json
  templates/basic/server.test.js
  templates/express_pg_sequelize/package.json
  test/help.test.js
  test/init.test.js
  test/list.test.js
  test/version.test.js
Labels: enhancement, feature, AMWOC, AMWOC-accepted

#86 Docker Compose generated using User Prompts
  README.md
  bin/configs.js
  bin/index.js
  bin/util/docker.js
  bin/util/menu.js
  package.json
  templates/Docker/express/Dockerfile
  templates/basic/.env
  templates/basic/package.json
  templates/basic/server.js
  templates/basic_ts/.env
  templates/basic_ts/package.json
  templates/basic_ts/src/index.ts
  templates/express_mysql/.env
  templates/express_mysql/config/appConfig.js
  templates/express_oauth_google/.env
  templates/express_oauth_google/index.js
  templates/express_oauth_microsoft/.env
  templates/express_oauth_microsoft/index.js
  templates/express_pg/.env
  templates/express_pg/config/appConfig.js
  templates/express_pg_prisma/.env
  templates/express_pg_prisma/package.json
  templates/express_pg_prisma/src/index.ts
  templates/express_pg_sequelize/.env
  templates/express_pg_sequelize/config/appConfig.js
  templates/express_pg_sequelize/db.js
  templates/express_pg_sequelize/index.js
  templates/express_pg_sequelize/package.json
  test/init.test.js
  test/list.test.js
Labels: feature, AMWOC, AMWOC-accepted

#93 [COMPLETED] express_mongo template created
  README.md
  bin/configs.js
  bin/index.js
  templates/express_mongo/.env
  templates/express_mongo/config/appConfig.js
  templates/express_mongo/connection/connection.js
  templates/express_mongo/controller/sampleController.js
  templates/express_mongo/db/reInitDb.js
  templates/express_mongo/db/seedData.json
  templates/express_mongo/index.js
  templates/express_mongo/logs/initLog.js
  templates/express_mongo/package.json
  templates/express_mongo/router/sampleRouter.js
  templates/express_mysql/config/appConfig.js
  templates/express_pg/config/appConfig.js
  test/init.test.js
  test/list.test.js
Labels: feature, AMWOC, AMWOC-accepted

#105 Bump qse version to 2.0
  README.md
  bin/configs.js
  package.json
Labels: release
